/**
 * src/demo/catalog.js
 *
 * Static content pools for the demo world: the people, the places, the
 * services, the vocabulary. world.js combines these with the seeded RNG to
 * build a coherent fake company.
 *
 * Everything in here is invented. Two deliberate safety properties:
 *
 *   1. Every phone number uses the 555-01XX exchange, which the North American
 *      Numbering Plan permanently reserves for fiction. No number generated by
 *      this demo can ever ring a real person.
 *   2. Street numbers and names are combinatorial, not sourced. Names are drawn
 *      from common-surname / common-given-name pools and paired at random, so a
 *      collision with a real customer is coincidence, not leakage.
 */

// ---------------------------------------------------------------------------
// The company
// ---------------------------------------------------------------------------

const COMPANY = {
  name: "Grounded Home Services",
  shortName: "GHS",
  legalName: "Grounded Home Services, LLC",
  domain: "groundedhomeservices.example",
  emailDomain: "groundedhs.example",
  tagline: "Plumbing · Heating · Cooling",
  phone: "(614) 555-0100",
  address: {
    street: "4120 Kettle Creek Road",
    city: "Ridgemont",
    state: "OH",
    zip: "43064",
    country: "USA",
  },
  // Fiscal year runs Oct 1 -> Sep 30, matching the original tenant's setup so
  // the fiscal-year rollup pages have something interesting to show.
  fiscalYearStartMonth: 10,
};

// ---------------------------------------------------------------------------
// Geography — a fictional metro area
// ---------------------------------------------------------------------------

const CITIES = [
  { name: "Ridgemont", zip: "43064", weight: 22 },
  { name: "Cedar Hollow", zip: "43065", weight: 16 },
  { name: "Fairview Crossing", zip: "43071", weight: 14 },
  { name: "Northgate", zip: "43082", weight: 12 },
  { name: "Stonebridge", zip: "43035", weight: 10 },
  { name: "Willow Bend", zip: "43016", weight: 9 },
  { name: "Harper Mills", zip: "43021", weight: 7 },
  { name: "Lake Verona", zip: "43040", weight: 5 },
  { name: "Grantsville", zip: "43054", weight: 3 },
  { name: "Ashford", zip: "43074", weight: 2 },
];

const STATE = "OH";

const STREET_NAMES = [
  "Maple", "Oak", "Cedar", "Birch", "Sycamore", "Chestnut", "Walnut", "Willow",
  "Hawthorn", "Juniper", "Aspen", "Magnolia", "Dogwood", "Laurel", "Hickory",
  "Meadowlark", "Quail Run", "Foxglove", "Heron", "Kingfisher", "Bluebird",
  "Millstone", "Quarry", "Ironwood", "Copperfield", "Stonegate", "Kettle Creek",
  "Prairie", "Harvest", "Orchard", "Cider Press", "Windmill", "Fieldstone",
  "Brookline", "Riverbend", "Still Water", "Cold Spring", "Falls Church",
  "Lantern", "Beacon", "Compass", "Meridian", "Summit", "Overlook", "Vista",
  "Whitfield", "Ainsworth", "Bramblewood", "Calloway", "Danbury", "Ellsworth",
  "Fenwick", "Granville", "Hollybrook", "Inglewood", "Jamesport", "Kingsley",
];

const STREET_SUFFIXES = [
  "St", "Ave", "Rd", "Dr", "Ln", "Ct", "Way", "Blvd", "Pl", "Ter", "Trl",
];

const UNIT_PREFIXES = ["Apt", "Unit", "Ste", "#"];

// ---------------------------------------------------------------------------
// People — name pools
// ---------------------------------------------------------------------------

const FIRST_NAMES_M = [
  "James", "Michael", "Robert", "David", "William", "Richard", "Thomas",
  "Daniel", "Matthew", "Anthony", "Mark", "Steven", "Paul", "Andrew", "Joshua",
  "Kevin", "Brian", "Eric", "Jason", "Ryan", "Jacob", "Gary", "Nicholas",
  "Stephen", "Larry", "Justin", "Scott", "Brandon", "Benjamin", "Samuel",
  "Gregory", "Alexander", "Patrick", "Jack", "Dennis", "Jerry", "Tyler",
  "Aaron", "Jose", "Adam", "Nathan", "Henry", "Douglas", "Zachary", "Peter",
  "Kyle", "Ethan", "Walter", "Noah", "Jeremy", "Christian", "Keith", "Roger",
  "Terry", "Austin", "Sean", "Gerald", "Carl", "Harold", "Dylan", "Arthur",
];

const FIRST_NAMES_F = [
  "Mary", "Patricia", "Jennifer", "Linda", "Elizabeth", "Barbara", "Susan",
  "Jessica", "Sarah", "Karen", "Lisa", "Nancy", "Betty", "Sandra", "Margaret",
  "Ashley", "Kimberly", "Emily", "Donna", "Michelle", "Carol", "Amanda",
  "Melissa", "Deborah", "Stephanie", "Rebecca", "Laura", "Sharon", "Cynthia",
  "Kathleen", "Amy", "Angela", "Shirley", "Anna", "Brenda", "Pamela", "Nicole",
  "Katherine", "Samantha", "Christine", "Rachel", "Catherine", "Debra",
  "Janet", "Carolyn", "Maria", "Heather", "Diane", "Julie", "Joyce", "Victoria",
  "Kelly", "Christina", "Joan", "Evelyn", "Lauren", "Judith", "Megan", "Andrea",
  "Cheryl", "Hannah", "Martha", "Jacqueline", "Frances", "Gloria", "Ann",
];

const LAST_NAMES = [
  "Anderson", "Bailey", "Barnett", "Bishop", "Blackwell", "Bowman", "Bradley",
  "Brennan", "Brooks", "Bryant", "Buchanan", "Calhoun", "Carlisle", "Chandler",
  "Chapman", "Colburn", "Coleman", "Conway", "Crawford", "Cummings", "Dalton",
  "Dawson", "Delaney", "Donovan", "Draper", "Duffy", "Eastman", "Ellington",
  "Fairbanks", "Farrell", "Fletcher", "Fontaine", "Fowler", "Gallagher",
  "Garrison", "Gilbert", "Glover", "Grayson", "Greenwood", "Hadley", "Halloran",
  "Hammond", "Harrington", "Hastings", "Hawkins", "Hensley", "Hollingsworth",
  "Holloway", "Hopkins", "Huntington", "Ingram", "Jennings", "Kendrick",
  "Kirkland", "Lambert", "Langford", "Lawson", "Ledbetter", "Lindstrom",
  "Lockhart", "Lowery", "Macklin", "Mansfield", "Marsden", "Mathis", "McAllister",
  "McKinney", "Merritt", "Middleton", "Montgomery", "Norwood", "Oakley",
  "Osborne", "Paxton", "Pemberton", "Pennington", "Prescott", "Quinlan",
  "Radcliffe", "Ramsey", "Redmond", "Rutherford", "Sanderson", "Sheridan",
  "Sinclair", "Slater", "Stafford", "Stanton", "Sutherland", "Thatcher",
  "Thornbury", "Tremaine", "Underwood", "Vandenberg", "Wakefield", "Waverly",
  "Whitaker", "Whitmore", "Winslow", "Woodruff", "Yeager", "Zimmerman",
];

const BUSINESS_NAME_PARTS = {
  prefix: [
    "Ridgemont", "Cedar Hollow", "Northgate", "Fairview", "Stonebridge",
    "Willow Bend", "Kettle Creek", "Harper", "Summit", "Meridian", "Lakeside",
  ],
  core: [
    "Property Group", "Dental", "Family Medicine", "Auto Center", "Bakery",
    "Veterinary Clinic", "Realty", "Storage", "Fitness", "Church of Christ",
    "Elementary School", "Animal Hospital", "Law Offices", "Coffee Roasters",
    "Apartments", "Senior Living", "Community Center", "Brewing Co.",
    "Hardware", "Print Shop", "Family Dentistry", "Physical Therapy",
  ],
};

// ---------------------------------------------------------------------------
// Staff — field technicians and office team
// ---------------------------------------------------------------------------
// Fixed (not RNG-generated) so that technician names are stable across the app
// and match the fleet vehicle mapping and the screenshots.

const TECHNICIANS = [
  { id: 9101, name: "Marcus Ellery",   role: "Technician", trade: "HVAC",     truck: "12", laborRate: 38, seniority: "lead"   },
  { id: 9102, name: "Dale Prentiss",   role: "Technician", trade: "HVAC",     truck: "14", laborRate: 34, seniority: "senior" },
  { id: 9103, name: "Trevor Nakamura", role: "Technician", trade: "HVAC",     truck: "17", laborRate: 31, seniority: "mid"    },
  { id: 9104, name: "Wes Calloway",    role: "Technician", trade: "Plumbing", truck: "21", laborRate: 37, seniority: "lead"   },
  { id: 9105, name: "Ivan Petrosyan",  role: "Technician", trade: "Plumbing", truck: "23", laborRate: 33, seniority: "senior" },
  { id: 9106, name: "Cole Baptiste",   role: "Technician", trade: "Plumbing", truck: "26", laborRate: 29, seniority: "mid"    },
  { id: 9107, name: "Jonah Whitfield", role: "Technician", trade: "Install",  truck: "31", laborRate: 35, seniority: "senior" },
  { id: 9108, name: "Andre Sokoloff",  role: "Technician", trade: "Install",  truck: "33", laborRate: 32, seniority: "mid"    },
  { id: 9109, name: "Reid Ferraro",    role: "Technician", trade: "HVAC",     truck: "18", laborRate: 27, seniority: "junior" },
  { id: 9110, name: "Sam Oyelaran",    role: "Technician", trade: "Plumbing", truck: "24", laborRate: 26, seniority: "junior" },
  { id: 9111, name: "Bryce Hallowell", role: "Apprentice", trade: "Install",  truck: "35", laborRate: 21, seniority: "appr"   },
  { id: 9112, name: "Nolan Vasquez",   role: "Technician", trade: "HVAC",     truck: "19", laborRate: 30, seniority: "mid"    },
];

const OFFICE_TEAM = [
  { id: 9201, name: "Priya Raghunathan", role: "Office Manager",       csr: true  },
  { id: 9202, name: "Danielle Cormier",  role: "Customer Service Rep", csr: true  },
  { id: 9203, name: "Renata Vasilenko",  role: "Customer Service Rep", csr: true  },
  { id: 9204, name: "Tomas Iriarte",     role: "Dispatcher",           csr: true  },
  { id: 9205, name: "Bea Lindqvist",     role: "Customer Service Rep", csr: true  },
  { id: 9206, name: "Harold Kittridge",  role: "Accounts Payable",     csr: false },
  { id: 9207, name: "Simone Achebe",     role: "Operations Analyst",   csr: false },
  { id: 9208, name: "Gus Vandermolen",   role: "Install Coordinator",  csr: true  },
];

const OWNERS = [
  { id: 9001, name: "Ellis Grounds",  role: "Owner" },
  { id: 9002, name: "Marguerite Ott", role: "Co-Owner" },
];

// ---------------------------------------------------------------------------
// ServiceTitan-shaped reference data
// ---------------------------------------------------------------------------

const BUSINESS_UNITS = [
  { id: 2001, name: "Service - HVAC",     active: true },
  { id: 2002, name: "Service - Plumbing", active: true },
  { id: 2003, name: "Install - HVAC",     active: true },
  { id: 2004, name: "Install - Plumbing", active: true },
  { id: 2005, name: "Maintenance Club",   active: true },
];

/**
 * Job types. The seven install ids (1232, 1227, 1229, 1233, 1234, 1216, 1208)
 * are load-bearing: src/config/installTrackerJobTypes.js filters on them by
 * number, so they must exist here with those exact ids or the Install Tracker
 * comes back empty.
 *
 * `membership: true` marks dues-covered visits. The Open Jobs report must never
 * flag these as missed invoices — they are paid for by the maintenance plan.
 */
const JOB_TYPES = [
  // --- Install (watched by the Install Tracker) ---
  { id: 1232, name: "HVAC Install",                  bu: 2003, category: "Install", weight: 3,  avgTicket: 11400, hours: 14 },
  { id: 1227, name: "Furnace Install",               bu: 2003, category: "Install", weight: 4,  avgTicket: 6200,  hours: 8  },
  { id: 1229, name: "Boiler Install",                bu: 2003, category: "Install", weight: 1,  avgTicket: 9800,  hours: 16 },
  { id: 1233, name: "Air Handler Install",           bu: 2003, category: "Install", weight: 2,  avgTicket: 5100,  hours: 7  },
  { id: 1234, name: "Condenser Install",             bu: 2003, category: "Install", weight: 3,  avgTicket: 5800,  hours: 7  },
  { id: 1216, name: "Water Heater Install",          bu: 2004, category: "Install", weight: 5,  avgTicket: 2450,  hours: 5  },
  { id: 1208, name: "Tankless Water Heater Install", bu: 2004, category: "Install", weight: 2,  avgTicket: 4700,  hours: 8  },

  // --- HVAC service ---
  { id: 1301, name: "HVAC Service Call",             bu: 2001, category: "Service", weight: 22, avgTicket: 385,  hours: 1.8 },
  { id: 1302, name: "AC Repair",                     bu: 2001, category: "Service", weight: 16, avgTicket: 520,  hours: 2.2 },
  { id: 1303, name: "Furnace Repair",                bu: 2001, category: "Service", weight: 14, avgTicket: 480,  hours: 2.1 },
  { id: 1304, name: "No Heat - Emergency",           bu: 2001, category: "Service", weight: 6,  avgTicket: 640,  hours: 2.6 },
  { id: 1305, name: "No Cool - Emergency",           bu: 2001, category: "Service", weight: 6,  avgTicket: 610,  hours: 2.5 },
  { id: 1306, name: "Duct Cleaning",                 bu: 2001, category: "Service", weight: 3,  avgTicket: 720,  hours: 4.0 },
  { id: 1307, name: "Thermostat Replacement",        bu: 2001, category: "Service", weight: 4,  avgTicket: 340,  hours: 1.2 },
  { id: 1308, name: "Mini Split Service",            bu: 2001, category: "Service", weight: 2,  avgTicket: 445,  hours: 2.0 },

  // --- Plumbing service ---
  { id: 1401, name: "Plumbing Service Call",         bu: 2002, category: "Service", weight: 20, avgTicket: 410,  hours: 1.9 },
  { id: 1402, name: "Drain Cleaning",                bu: 2002, category: "Service", weight: 12, avgTicket: 355,  hours: 1.6 },
  { id: 1403, name: "Water Heater Repair",           bu: 2002, category: "Service", weight: 8,  avgTicket: 465,  hours: 2.0 },
  { id: 1404, name: "Leak Repair",                   bu: 2002, category: "Service", weight: 9,  avgTicket: 540,  hours: 2.4 },
  { id: 1405, name: "Sewer Camera Inspection",       bu: 2002, category: "Service", weight: 3,  avgTicket: 395,  hours: 1.5 },
  { id: 1406, name: "Sump Pump Replacement",         bu: 2002, category: "Service", weight: 3,  avgTicket: 880,  hours: 3.0 },
  { id: 1407, name: "Fixture Replacement",           bu: 2002, category: "Service", weight: 5,  avgTicket: 620,  hours: 2.8 },
  { id: 1408, name: "Backflow Test",                 bu: 2002, category: "Service", weight: 4,  avgTicket: 165,  hours: 0.8 },
  { id: 1409, name: "Gas Line Repair",               bu: 2002, category: "Service", weight: 2,  avgTicket: 780,  hours: 3.2 },

  // --- Membership / maintenance (dues-covered: never a "missed invoice") ---
  { id: 1501, name: "PSM - Heating Maintenance",     bu: 2005, category: "Membership", weight: 11, avgTicket: 0, hours: 1.2, membership: true },
  { id: 1502, name: "PSM - Cooling Maintenance",     bu: 2005, category: "Membership", weight: 11, avgTicket: 0, hours: 1.2, membership: true },
  { id: 1503, name: "PSM - Plumbing Inspection",     bu: 2005, category: "Membership", weight: 5,  avgTicket: 0, hours: 1.0, membership: true },
  { id: 1504, name: "Ground Club - Annual Visit",    bu: 2005, category: "Membership", weight: 4,  avgTicket: 0, hours: 1.1, membership: true },

  // --- Warranty / callback / estimate (mostly $0, drive the margin outliers) ---
  { id: 1601, name: "Warranty Callback",             bu: 2001, category: "Warranty", weight: 5, avgTicket: 0,   hours: 1.7, noCharge: true },
  { id: 1602, name: "Return Visit - Parts",          bu: 2001, category: "Warranty", weight: 4, avgTicket: 0,   hours: 1.4, noCharge: true },
  { id: 1603, name: "Estimate / Consultation",       bu: 2003, category: "Sales",    weight: 7, avgTicket: 0,   hours: 1.0, noCharge: true },
  { id: 1604, name: "Second Opinion",                bu: 2001, category: "Sales",    weight: 2, avgTicket: 0,   hours: 1.0, noCharge: true },
];

const JOB_STATUSES = ["Scheduled", "Dispatched", "InProgress", "Hold", "Completed", "Canceled"];

const CAMPAIGNS = [
  { id: 3001, name: "Google LSA" },
  { id: 3002, name: "Google Search - Brand" },
  { id: 3003, name: "Google Search - Non-Brand" },
  { id: 3004, name: "Repeat Customer" },
  { id: 3005, name: "Referral - Customer" },
  { id: 3006, name: "Facebook - Seasonal Tune-Up" },
  { id: 3007, name: "Direct Mail - Spring" },
  { id: 3008, name: "Yard Sign / Truck" },
  { id: 3009, name: "Home Advisor" },
  { id: 3010, name: "Membership Renewal" },
];

const VENDORS = [
  { id: 4101, name: "Meridian Supply Co.",            active: true },
  { id: 4102, name: "Cardinal HVAC Wholesale",        active: true },
  { id: 4103, name: "Bluegrass Plumbing Supply",      active: true },
  { id: 4104, name: "Northgate Pipe & Fitting",       active: true },
  { id: 4105, name: "Ferris Industrial Distributors", active: true },
  { id: 4106, name: "Summit Parts Depot",             active: true },
  { id: 4107, name: "Kettle Creek Electrical Supply", active: true },
  { id: 4108, name: "Ridgemont Sheet Metal",          active: true },
  { id: 4109, name: "Anvil Tool & Fastener",          active: true },
  { id: 4110, name: "Great Lakes Refrigeration Sup.", active: true },
];

const EQUIPMENT_MANUFACTURERS = {
  hvac: [
    { name: "American Standard", models: ["S9V2-VS", "S8X1", "AM7A0B24", "4A6H6036", "S9X2C080", "GAM5A0B30"] },
    { name: "Trane",             models: ["XR14", "XV80", "S9X2", "XL16i", "TAM9A0B30"] },
    { name: "Goodman",           models: ["GSX140361", "GMVC80604", "ASPT47D14", "GSZ140361"] },
    { name: "Carrier",           models: ["24ABC6", "59SC5A", "FV4CNF003", "25HCB6"] },
  ],
  waterHeater: [
    { name: "Bradford White", models: ["RG240T6N", "RG250T6N", "M4TW50S6FBN", "RG1PV50S6N"] },
    { name: "Rinnai",         models: ["RU199iN", "RU160iN", "RUR199iN", "V65iN"] },
    { name: "A.O. Smith",     models: ["GCR-40", "GPVX-50L", "ENS-40"] },
  ],
};

// ---------------------------------------------------------------------------
// Pricebook seed material
// ---------------------------------------------------------------------------

const PRICEBOOK_SERVICES = [
  ["HVAC Diagnostic Fee",              "SVC-DIAG-HVAC",  129, 99],
  ["Plumbing Diagnostic Fee",          "SVC-DIAG-PLB",   119, 89],
  ["After Hours Diagnostic",           "SVC-DIAG-AH",    229, 179],
  ["Capacitor Replacement",            "SVC-CAP-01",     289, 231],
  ["Contactor Replacement",            "SVC-CONT-01",    265, 212],
  ["Blower Motor Replacement",         "SVC-BLWR-01",    895, 716],
  ["Condenser Fan Motor Replacement",  "SVC-CFM-01",     742, 594],
  ["Evaporator Coil Cleaning",         "SVC-COIL-01",    485, 388],
  ["Refrigerant Recharge - R410A",     "SVC-R410-01",    118, 94],
  ["Ignitor Replacement",              "SVC-IGN-01",     318, 254],
  ["Flame Sensor Clean & Test",        "SVC-FLAME-01",   165, 132],
  ["Inducer Motor Replacement",        "SVC-IND-01",     812, 650],
  ["Heat Exchanger Inspection",        "SVC-HX-01",      210, 168],
  ["Thermostat - Smart Install",       "SVC-TSTAT-SM",   489, 391],
  ["Thermostat - Programmable Install","SVC-TSTAT-PR",   289, 231],
  ["Condensate Pump Replacement",      "SVC-CDP-01",     345, 276],
  ["Drain Line Clear - Kitchen",       "SVC-DRN-KIT",    295, 236],
  ["Drain Line Clear - Main",          "SVC-DRN-MAIN",   425, 340],
  ["Hydro Jetting - Main Line",        "SVC-JET-01",     895, 716],
  ["Sewer Camera Inspection",          "SVC-CAM-01",     395, 316],
  ["Toilet Rebuild Kit",               "SVC-TOI-RB",     289, 231],
  ["Toilet Replacement - Standard",    "SVC-TOI-RPL",    685, 548],
  ["Kitchen Faucet Replacement",       "SVC-FCT-KIT",    465, 372],
  ["Bath Faucet Replacement",          "SVC-FCT-BTH",    398, 318],
  ["Garbage Disposal Replacement",     "SVC-DISP-01",    525, 420],
  ["Water Heater Flush",               "SVC-WH-FLUSH",   189, 151],
  ["Water Heater T&P Valve",           "SVC-WH-TP",      245, 196],
  ["Thermocouple Replacement",         "SVC-WH-TC",      228, 182],
  ["Expansion Tank Install",           "SVC-EXP-01",     385, 308],
  ["Pressure Reducing Valve",          "SVC-PRV-01",     645, 516],
  ["Main Shutoff Valve Replacement",   "SVC-MSV-01",     735, 588],
  ["Hose Bib Replacement",             "SVC-HB-01",      295, 236],
  ["Sump Pump - 1/3 HP Replacement",   "SVC-SUMP-33",    885, 708],
  ["Sump Pump - Battery Backup",       "SVC-SUMP-BB",   1485, 1188],
  ["Backflow Preventer Test",          "SVC-BF-TEST",    165, 132],
  ["Backflow Preventer Rebuild",       "SVC-BF-RB",      485, 388],
  ["Gas Line Leak Test",               "SVC-GAS-TEST",   285, 228],
  ["Gas Line Repair - Per Foot",       "SVC-GAS-FT",      68,  54],
  ["Precision Tune-Up - Heating",      "SVC-PTU-HEAT",   149, 119],
  ["Precision Tune-Up - Cooling",      "SVC-PTU-COOL",   149, 119],
  ["Duct Cleaning - Whole Home",       "SVC-DUCT-WH",    749, 599],
  ["UV Air Purifier Install",          "SVC-UV-01",      985, 788],
  ["Whole Home Humidifier Install",    "SVC-HUM-01",    1185, 948],
  ["Media Filter Cabinet Install",     "SVC-FLT-01",     585, 468],
  ["Mini Split Deep Clean",            "SVC-MS-CLEAN",   425, 340],
  ["Emergency Water Shutoff",          "SVC-EMER-WS",    285, 228],
];

const PRICEBOOK_MATERIALS = [
  ["Run Capacitor 45/5 MFD 370V",   "MAT-CAP-455",     48.00, 14.20],
  ["Run Capacitor 35/5 MFD 440V",   "MAT-CAP-355",     44.00, 12.80],
  ["Dual Run Capacitor 60/5 MFD",   "MAT-CAP-605",     62.00, 19.40],
  ["Contactor 1P 30A 24V",          "MAT-CONT-1P30",   38.00, 11.50],
  ["Contactor 2P 40A 24V",          "MAT-CONT-2P40",   52.00, 16.10],
  ["Hot Surface Ignitor - Univ.",   "MAT-IGN-UNIV",    64.00, 21.30],
  ["Flame Sensor - Universal",      "MAT-FLAME-U",     28.00,  8.40],
  ["Transformer 40VA 24V",          "MAT-XFMR-40",     42.00, 13.60],
  ["Fan Limit Switch",              "MAT-FLS-01",      56.00, 18.90],
  ["Pressure Switch - Universal",   "MAT-PSW-U",       78.00, 26.40],
  ["Condensate Pump 115V",          "MAT-CDP-115",    118.00, 41.00],
  ["Condensate Safety Switch",      "MAT-CSS-01",      22.00,  6.10],
  ["R-410A Refrigerant - per lb",   "MAT-R410-LB",     86.00, 29.50],
  ["Refrigerant Line Set 3/4x3/8",  "MAT-LINE-3438",  185.00, 74.00],
  ["Filter Drier - Liquid Line",    "MAT-DRIER-01",    46.00, 15.20],
  ["Schrader Valve Core Kit",       "MAT-SCHR-01",     14.00,  3.90],
  ["16x25x1 Pleated Filter",        "MAT-FLT-16251",   18.00,  5.20],
  ["20x25x5 Media Filter",          "MAT-FLT-20255",   72.00, 26.00],
  ["Smart Thermostat - WiFi",       "MAT-TSTAT-WIFI", 289.00, 148.00],
  ["Programmable Thermostat",       "MAT-TSTAT-PROG", 128.00, 52.00],
  ["Thermostat Wire 18/8 - per ft", "MAT-TWIRE-188",    1.35,  0.42],
  ["Wax Ring Kit - Extra Thick",    "MAT-WAX-XT",      16.00,  4.10],
  ["Toilet Fill Valve",             "MAT-TFV-01",      32.00,  9.80],
  ["Toilet Flapper - Universal",    "MAT-FLAP-U",      14.00,  3.60],
  ["Angle Stop 1/2 x 3/8 Quarter",  "MAT-STOP-QT",     24.00,  7.20],
  ["Braided Supply Line 20in",      "MAT-SUP-20",      18.00,  5.40],
  ["PEX-A 1/2in - per ft",          "MAT-PEX-12",       1.85,  0.58],
  ["PEX-A 3/4in - per ft",          "MAT-PEX-34",       2.65,  0.86],
  ["Copper Type L 1/2in - per ft",  "MAT-CU-12",        6.40,  2.35],
  ["Copper Type L 3/4in - per ft",  "MAT-CU-34",        9.80,  3.70],
  ["ProPress Coupling 1/2in",       "MAT-PP-C12",      12.50,  4.10],
  ["ProPress Elbow 3/4in",          "MAT-PP-E34",      18.00,  6.20],
  ["Ball Valve 3/4in Full Port",    "MAT-BV-34",       34.00, 11.40],
  ["PVC Sch40 3in - per ft",        "MAT-PVC-3",        7.20,  2.60],
  ["ABS Closet Flange 4in",         "MAT-FLNG-4",      28.00,  9.10],
  ["Sump Pump 1/3 HP Cast Iron",    "MAT-SUMP-33",    285.00, 142.00],
  ["Sump Check Valve 1-1/2in",      "MAT-SCV-15",      38.00, 12.60],
  ["Thermal Expansion Tank 2 Gal",  "MAT-EXP-2",      118.00, 47.00],
  ["T&P Relief Valve 3/4in",        "MAT-TP-34",       46.00, 15.80],
  ["Water Heater Thermocouple",     "MAT-WH-TC",       28.00,  8.90],
  ["Dielectric Union 3/4in",        "MAT-DU-34",       22.00,  7.30],
  ["Gas Flex Connector 3/4x24",     "MAT-GAS-F24",     34.00, 11.20],
  ["CSST 1/2in - per ft",           "MAT-CSST-12",      3.90,  1.28],
  ["Pipe Thread Sealant 8oz",       "MAT-PTS-8",       14.00,  4.60],
  ["Backflow Repair Kit 3/4in",     "MAT-BF-KIT34",   146.00, 58.00],
  ["Sheet Metal Screws #8 - 100ct", "MAT-SMS-8",       11.00,  3.10],
  ["Foil Tape 2in x 60yd",          "MAT-TAPE-F2",     16.00,  5.30],
  ["Flex Duct R8 8in x 25ft",       "MAT-DUCT-R8-8",   96.00, 38.00],
];

const PRICEBOOK_EQUIPMENT = [
  ["2 Ton 14.3 SEER2 Condenser",        "EQP-CND-24-143",  2480, 1420],
  ["2.5 Ton 14.3 SEER2 Condenser",      "EQP-CND-30-143",  2695, 1545],
  ["3 Ton 14.3 SEER2 Condenser",        "EQP-CND-36-143",  2890, 1660],
  ["3.5 Ton 14.3 SEER2 Condenser",      "EQP-CND-42-143",  3150, 1810],
  ["4 Ton 14.3 SEER2 Condenser",        "EQP-CND-48-143",  3390, 1950],
  ["5 Ton 14.3 SEER2 Condenser",        "EQP-CND-60-143",  3720, 2140],
  ["3 Ton 16 SEER2 Two-Stage Condenser","EQP-CND-36-16TS", 4180, 2400],
  ["80% 60k BTU Single Stage Furnace",  "EQP-FRN-80-60",   2240, 1290],
  ["80% 80k BTU Single Stage Furnace",  "EQP-FRN-80-80",   2410, 1385],
  ["80% 100k BTU Two Stage Furnace",    "EQP-FRN-80-100",  2980, 1715],
  ["96% 60k BTU Variable Furnace",      "EQP-FRN-96-60",   3480, 2000],
  ["96% 80k BTU Variable Furnace",      "EQP-FRN-96-80",   3690, 2120],
  ["96% 100k BTU Variable Furnace",     "EQP-FRN-96-100",  3950, 2270],
  ["Air Handler 2 Ton Multi-Speed",     "EQP-AH-24",       1580,  910],
  ["Air Handler 3 Ton Variable",        "EQP-AH-36V",      2190, 1260],
  ["Air Handler 4 Ton Variable",        "EQP-AH-48V",      2470, 1420],
  ["Evaporator Coil 3 Ton Cased",       "EQP-COIL-36",      985,  565],
  ["Evaporator Coil 4 Ton Cased",       "EQP-COIL-48",     1120,  645],
  ["40 Gal Atmospheric Water Heater",   "EQP-WH-40A",       985,  520],
  ["50 Gal Atmospheric Water Heater",   "EQP-WH-50A",      1140,  605],
  ["50 Gal Power Vent Water Heater",    "EQP-WH-50PV",     1780,  945],
  ["75 Gal Power Vent Water Heater",    "EQP-WH-75PV",     2640, 1400],
  ["Tankless WH 199k BTU Indoor",       "EQP-WH-TL199",    2980, 1620],
  ["Tankless WH 160k BTU Indoor",       "EQP-WH-TL160",    2540, 1380],
  ["Mini Split 12k BTU Single Zone",    "EQP-MS-12",       1980, 1140],
  ["Mini Split 24k BTU Dual Zone",      "EQP-MS-24D",      3480, 2000],
  ["Whole Home Humidifier - Bypass",    "EQP-HUM-BP",       620,  355],
  ["UV Air Purifier - Dual Lamp",       "EQP-UV-2L",        740,  425],
  ["Media Air Cleaner Cabinet 20x25",   "EQP-MAC-2025",     385,  220],
  ["Boiler 100k BTU Cast Iron",         "EQP-BLR-100",     5480, 3150],
];

const PRICEBOOK_FEES = [
  ["Trip Charge",                 "FEE-TRIP",         89,  89],
  ["After Hours Surcharge",       "FEE-AH",          145, 145],
  ["Weekend Surcharge",           "FEE-WKND",        115, 115],
  ["Permit Fee - Mechanical",     "FEE-PERMIT-M",    185, 185],
  ["Permit Fee - Plumbing",       "FEE-PERMIT-P",    165, 165],
  ["Haul Away / Disposal",        "FEE-HAUL",         95,  95],
  ["Ground Club Membership",      "FEE-CLUB",        219, 219],
  ["Ground Club - Free Year",     "FEE-CLUB-FREE",     0,   0],
  ["Senior Discount",             "DSC-SENIOR",      -50, -50],
  ["Military Discount",           "DSC-MIL",         -50, -50],
  ["Member Repair Discount 15%",  "DSC-MEMBER-15",     0,   0],
  ["Financing Buy-Down Fee",      "FEE-FIN-BD",      285, 285],
];

// ---------------------------------------------------------------------------
// Call intelligence vocabulary
// ---------------------------------------------------------------------------

const CALL_TYPES = ["Booked", "Unbooked", "Excused", "NotLead", "Abandoned"];

const CALL_REASONS = [
  { id: 5001, name: "No Heat",              type: "Booked"    },
  { id: 5002, name: "No Cool",              type: "Booked"    },
  { id: 5003, name: "Service - Repair",     type: "Booked"    },
  { id: 5004, name: "Maintenance Visit",    type: "Booked"    },
  { id: 5005, name: "Estimate Request",     type: "Booked"    },
  { id: 5006, name: "Water Heater",         type: "Booked"    },
  { id: 5007, name: "Drain / Sewer",        type: "Booked"    },
  { id: 5008, name: "Reschedule",           type: "Excused"   },
  { id: 5009, name: "ETA Check",            type: "Excused"   },
  { id: 5010, name: "Billing Question",     type: "Excused"   },
  { id: 5011, name: "Vendor/marketing",     type: "Excused"   },
  { id: 5012, name: "Employee - Internal",  type: "Excused"   },
  { id: 5013, name: "Price Too High",       type: "Unbooked"  },
  { id: 5014, name: "Out of Service Area",  type: "NotLead"   },
  { id: 5015, name: "Wrong Number",         type: "NotLead"   },
  { id: 5016, name: "Solicitation",         type: "NotLead"   },
  { id: 5017, name: "Scheduling Conflict",  type: "Unbooked"  },
  { id: 5018, name: "Warranty Question",    type: "Excused"   },
  { id: 5019, name: "Hung Up",              type: "Abandoned" },
  { id: 5020, name: "Membership Signup",    type: "Booked"    },
];

/**
 * Known-caller rules for the demo tenant. Mirrors the shape of
 * src/config/knownCallers.js — a supply house that calls for card
 * authorization and always gets handled by the same CSR.
 */
const DEMO_KNOWN_CALLERS = [
  {
    phone: "(614) 555-0177",
    label: "Supply house - card authorization",
    callType: "Excused",
    reason: "Vendor/marketing",
    agentId: 9203,
    agentName: "Renata Vasilenko",
  },
  {
    phone: "(330) 555-0164",
    label: "Parts distributor - order status",
    callType: "Excused",
    reason: "Vendor/marketing",
    agentId: 9206,
    agentName: "Harold Kittridge",
  },
];

module.exports = {
  COMPANY,
  CITIES,
  STATE,
  STREET_NAMES,
  STREET_SUFFIXES,
  UNIT_PREFIXES,
  FIRST_NAMES_M,
  FIRST_NAMES_F,
  LAST_NAMES,
  BUSINESS_NAME_PARTS,
  TECHNICIANS,
  OFFICE_TEAM,
  OWNERS,
  BUSINESS_UNITS,
  JOB_TYPES,
  JOB_STATUSES,
  CAMPAIGNS,
  VENDORS,
  EQUIPMENT_MANUFACTURERS,
  PRICEBOOK_SERVICES,
  PRICEBOOK_MATERIALS,
  PRICEBOOK_EQUIPMENT,
  PRICEBOOK_FEES,
  CALL_TYPES,
  CALL_REASONS,
  DEMO_KNOWN_CALLERS,
};
